import type { ReferenceItem } from "../types/chat.js";

export const HITESH_CATALOG: ReferenceItem[] = [
  {
    title: "Chai aur Springboot - Java Backend Series",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLAtsKd9vhf5M",
    topics: ["spring boot", "java", "backend", "microservices", "production"],
    free: true,
  },
  {
    title: "Chai aur DSA - Data Structures & Algorithms (Hindi)",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoAMcPw8uJXxjeLwYQV8MkpQ",
    topics: ["dsa", "data structures", "algorithms", "interview prep", "hindi"],
    free: true,
  },
  {
    title: "Chai aur Mobile Development",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBLai4myIIkzhZFL4SiL9EA",
    topics: ["mobile development", "android", "ios", "react native", "flutter"],
    free: true,
  },
  {
    title: "Chai aur TypeScript",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBkkr8lblqtsJvxrw3j1tWC",
    topics: ["typescript", "javascript", "type safety", "frontend", "backend"],
    free: true,
  },
  {
    title: "Chai aur C++",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoCPfgKZS8UE0MDuwiKvL8zi",
    topics: ["c++", "competitive programming", "data structures", "algorithms"],
    free: true,
  },
  {
    title: "Chai aur Django",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDOf-6vAcKmazT92uLnWAgy",
    topics: ["django", "python", "backend", "web development"],
    free: true,
  },
  {
    title: "Chai aur Next.js",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBAaWGtn9GA2PTw0HO0tXzq",
    topics: ["nextjs", "react", "server-side rendering", "frontend"],
    free: true,
  },
  {
    title: "Chai aur Python",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBsMugTFALhdLlZ5VOqCg2s",
    topics: ["python", "scripting", "backend", "automation"],
    free: true,
  },
  {
    title: "Chai aur Backend - Node.js, Express & MongoDB",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBGh_8p_NS-ZAh6v7HhYqHW",
    topics: ["backend", "nodejs", "express", "mongodb", "rest api", "authentication"],
    free: true,
  },
  {
    title: "Chai aur React",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDqgPchmvIsL4hTnJIrtige",
    topics: ["react", "frontend", "hooks", "jsx", "components"],
    free: true,
  },
  {
    title: "Chai aur JavaScript",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBuX3f4EOACle2y-tRC5Q37",
    topics: ["javascript", "js fundamentals", "frontend", "backend"],
    free: true,
  },
  {
    title: "Chai aur HTML",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDBNF5s-WH6aLbthSEIMhMI",
    topics: ["html", "web fundamentals", "frontend", "beginner"],
    free: true,
  },
  {
    title: "Hitesh Choudhary - English Channel (MERN & JavaScript)",
    platform: "youtube",
    type: "handle",
    url: "https://www.youtube.com/@HiteshCodeLab",
    topics: ["mern", "javascript", "react", "general programming"],
    free: true,
  },
  {
    title: "Deploy to Production (English)",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWSNLlI_I2xSDdghk3Y0zGml",
    topics: ["production", "deployment", "devops", "cloud", "servers"],
    free: true,
  },
  {
    title: "Git for Beginners (English)",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWT4v4iK1h6qejyhGObFH9_o",
    topics: ["git", "github", "version control", "collaboration"],
    free: true,
  },
  {
    title: "React Native Mastery (English)",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWSjBBJ-egNNOd4mdblt1P4c",
    topics: ["react native", "mobile development", "frontend", "cross-platform"],
    free: true,
  },
  {
    title: "ChaiCode - Products & Reviews",
    platform: "website",
    type: "post",
    url: "https://chaicode.com",
    topics: ["chaicode", "products", "reviews", "student outcomes"],
    free: true,
  },
  {
    title: "ChaiCode Cohorts",
    platform: "website",
    type: "cohort",
    url: "https://chaicode.com/#cohort",
    topics: ["full stack", "structured learning", "mentorship", "live cohort"],
    free: false,
  },
  {
    title: "ChaiCode Courses",
    platform: "website",
    type: "course",
    url: "https://courses.chaicode.com/learn",
    topics: ["structured courses", "full stack", "self-paced learning"],
    free: false,
  },
  {
    title: "Chai aur Docs - Companion Documentation",
    platform: "website",
    type: "post",
    url: "https://docs.chaicode.com",
    topics: ["documentation", "reference notes", "devops", "backend", "git"],
    free: true,
  },
  {
    title: "Hitesh Choudhary - Courses on Udemy",
    platform: "udemy",
    type: "course",
    url: "https://www.udemy.com/user/hitesh-choudharycom/",
    topics: ["structured courses", "javascript", "web development"],
    free: false,
  },
  {
    title: "Hitesh Choudhary - Personal Website",
    platform: "website",
    type: "post",
    url: "https://hiteshchoudhary.com",
    topics: ["about", "background", "career", "philosophy"],
    free: true,
  },
  {
    title: "Chai aur Code - Hinglish Channel",
    platform: "youtube",
    type: "handle",
    url: "https://www.youtube.com/@chaiaurcode",
    topics: ["quick concepts", "tips", "career advice", "short videos"],
    free: true,
  },
  {
    title: "Hitesh Choudhary on Instagram",
    platform: "social",
    type: "handle",
    url: "https://www.instagram.com/hiteshchoudharyofficial/",
    topics: ["behind the scenes", "personal updates", "reels"],
    free: true,
  },
  {
    title: "Hitesh Choudhary on LinkedIn",
    platform: "social",
    type: "handle",
    url: "https://www.linkedin.com/in/hiteshchoudhary/",
    topics: ["professional updates", "career", "networking"],
    free: true,
  },
  {
    title: "Hitesh Choudhary on GitHub",
    platform: "social",
    type: "handle",
    url: "https://github.com/hiteshchoudhary",
    topics: ["open source", "repositories", "code samples"],
    free: true,
  },
  {
    title: "Hitesh Choudhary on X",
    platform: "social",
    type: "handle",
    url: "https://x.com/hiteshdotcom",
    topics: ["quick takes", "career advice", "industry opinions"],
    free: true,
  },
];
