import type { ReferenceItem } from "../types/chat.js";

export const HITESH_CATALOG: ReferenceItem[] = [
  {
    title: "Chai aur Springboot",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLAtsKd9vhf5M",
    topics: ["springboot", "java", "backend", "microservices", "production"],
    free: true,
  },
  {
    title: "Chai aur DSA (Hindi)",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoAMcPw8uJXxjeLwYQV8MkpQ",
    topics: ["dsa", "data structures", "algorithms", "hindi"],
    free: true,
  },
  {
    title: "Chai aur Mobile Development",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBLai4myIIkzhZFL4SiL9EA",
    topics: ["mobile", "android", "ios", "react native", "flutter"],
    free: true,
  },
  {
    title: "Chai aur Typescript",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBkkr8lblqtsJvxrw3j1tWC",
    topics: ["typescript", "ts", "javascript", "js", "frontend", "backend"],
    free: true,
  },
  {
    title: "Chai aur C++",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoCPfgKZS8UE0MDuwiKvL8zi",
    topics: ["c++", "cpp", "programming", "backend", "data structures"],
    free: true,
  },
  {
    title: "Chai aur Django",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDOf-6vAcKmazT92uLnWAgy",
    topics: ["django", "python", "backend", "web development"],
    free: true,
  },
  {
    title: "Chai aur NextJS",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBAaWGtn9GA2PTw0HO0tXzq",
    topics: ["nextjs", "react", "frontend", "server-side rendering"],
    free: true,
  },
  {
    title: "Chai aur Python",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBsMugTFALhdLlZ5VOqCg2s",
    topics: ["python", "programming", "backend", "web development"],
    free: true,
  },
  {
    title: "Chai aur Backend",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBGh_8p_NS-ZAh6v7HhYqHW",
    topics: ["backend", "nodejs", "express", "mongodb", "rest api", "auth"],
    free: true,
  },
  {
    title: "Chai aur React",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDqgPchmvIsL4hTnJIrtige",
    topics: ["react", "frontend", "hooks", "jsx", "components"],
    free: true,
  },
  {
    title: "Chai aur JavaScript",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoBuX3f4EOACle2y-tRC5Q37",
    topics: ["javascript", "js", "frontend", "backend"],
    free: true,
  },
  {
    title: "Chai aur HTML",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLu71SKxNbfoDBNF5s-WH6aLbthSEIMhMI",
    topics: ["html", "web development", "frontend"],
    free: true,
  },
  {
    title: "Hitesh Choudhary (English Channel)",
    platform: "youtube",
    type: "handle",
    url: "https://www.youtube.com/@HiteshCodeLab",
    topics: ["mern", "javascript", "react", "general programming"],
    free: true,
  },
  {
    title: "Deploy to Production (English)",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWSNLlI_I2xSDdghk3Y0zGml",
    topics: ["production", "deployment", "cloud"],
    free: true,
  },
  {
    title: "Git for Beginners (English)",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWT4v4iK1h6qejyhGObFH9_o",
    topics: ["git", "version control", "development"],
    free: true,
  },
  {
    title: "React Native Mastery (English)",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/playlist?list=PLRAV69dS1uWSjBBJ-egNNOd4mdblt1P4c",
    topics: ["react native", "mobile", "frontend"],
    free: true,
  },
  {
    title: "ChaiCode",
    platform: "website",
    type: "post",
    url: "https://chaicode.com",
    topics: ["cohorts", "udemy", "products", "reviews"],
    free: true,
  },
  {
    title: "ChaiCode Cohorts",
    platform: "website",
    type: "cohort",
    url: "https://chaicode.com/#cohort",
    topics: ["full stack", "structured learning", "mentorship", "live cohort"],
    free: false,
  },
  {
    title: "ChaiCode Courses",
    platform: "website",
    type: "course",
    url: "https://courses.chaicode.com",
    topics: [],
    free: false,
  },
  {
    title: "Chai aur Docs (Companion Documentation)",
    platform: "website",
    type: "post",
    url: "https://docs.chaicode.com",
    topics: ["documentation", "reference notes", "devops", "backend"],
    free: true,
  },

  {
    title: "Courses on Udemy",
    platform: "udemy",
    type: "course",
    url: "https://www.udemy.com/user/hitesh-choudharycom/",
    topics: ["structured courses", "javascript", "web development"],
    free: false,
  },
  {
    title: "Hitesh Choudhary Portfolio Website",
    platform: "website",
    type: "post",
    url: "https://hiteshchoudhary.com",
    topics: ["about", "background", "career", "philosophy"],
    free: true,
  },
  {
    title: "Chai aur Code (Hinglish Channel)",
    platform: "youtube",
    type: "handle",
    url: "https://www.youtube.com/@chaiaurcode",
    topics: ["quick concepts", "tips", "career", "short videos"],
    free: true,
  },
  {
    title: "Hitesh Choudhary on Instagram",
    platform: "social",
    type: "handle",
    url: "https://www.instagram.com/hiteshchoudharyofficial/",
    topics: [],
    free: true,
  },
  {
    title: "Hitesh Choudhary on LinkedIn",
    platform: "social",
    type: "handle",
    url: "https://www.linkedin.com/in/hiteshchoudhary/",
    topics: [],
    free: true,
  },
  {
    title: "Hitesh Choudhary on Github",
    platform: "social",
    type: "handle",
    url: "https://github.com/hiteshchoudhary",
    topics: [],
    free: true,
  },
  {
    title: "Hitesh Choudhary on X",
    platform: "social",
    type: "handle",
    url: "https://x.com/hiteshdotcom",
    topics: ["quick takes", "career advice", "industry opinions"],
    free: true,
  },
];
