import type { ReferenceItem } from "../types/chat.js";

export const HITESH_CATALOG: ReferenceItem[] = [
  {
    title: "Chai aur React",
    platform: "youtube",
    type: "series",
    url: "https://www.youtube.com/@chaiaurcode",
    topics: ["react", "frontend", "hooks", "jsx", "components"],
    free: true,
  },
  {
    title: "Chai aur Backend",
    platform: "youtube",
    type: "series",
    url: "https://github.com/hiteshchoudhary/chai-backend",
    topics: ["backend", "nodejs", "express", "mongodb", "rest api", "auth"],
    free: true,
  },
  {
    title: "Chai aur DevOps (Deploy to Production)",
    platform: "youtube",
    type: "series",
    url: "https://docs.chaicode.com/youtube/chai-aur-devops/welcome/",
    topics: ["devops", "deployment", "docker", "ci/cd", "servers", "production"],
    free: true,
  },
  {
    title: "Cutting Chai",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/@chaiaurcode",
    topics: ["quick concepts", "tips", "career", "short videos"],
    free: true,
  },
  {
    title: "JS Hindi — JavaScript Fundamentals",
    platform: "youtube",
    type: "series",
    url: "https://github.com/hiteshchoudhary/js-hindi-youtube",
    topics: ["javascript", "js fundamentals", "hindi", "basics"],
    free: true,
  },
  {
    title: "Hitesh Choudhary channel (MERN, JS, general dev)",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/@HiteshChoudharydotcom",
    topics: ["mern", "javascript", "react", "general programming"],
    free: true,
  },
  {
    title: "ChaiCode Cohorts",
    platform: "cohort",
    type: "course",
    url: "https://chaicode.com",
    topics: ["full stack", "structured learning", "mentorship", "live cohort"],
    free: false,
  },
  {
    title: "Chai aur Docs (companion documentation)",
    platform: "website",
    type: "post",
    url: "https://docs.chaicode.com",
    topics: ["documentation", "reference notes", "devops", "backend"],
    free: true,
  },
  {
    title: "Courses on Udemy",
    platform: "udemy",
    type: "course",
    url: "https://www.udemy.com/user/hitesh-choudharycom/",
    topics: ["structured courses", "javascript", "web development"],
    free: false,
  },
  {
    title: "hiteshchoudhary.com",
    platform: "website",
    type: "post",
    url: "https://hiteshchoudhary.com",
    topics: ["about", "background", "career", "philosophy"],
    free: true,
  },
  {
    title: "@Hiteshdotcom on X",
    platform: "social",
    type: "handle",
    url: "https://x.com/Hiteshdotcom",
    topics: ["quick takes", "career advice", "industry opinions"],
    free: true,
  },
];
