import type { ReferenceItem } from "@/types/chat.js";

export const PIYUSH_CATALOG: ReferenceItem[] = [
  {
    title: "Piyush Garg - Personal Website",
    platform: "website",
    type: "post",
    url: "https://www.piyushgarg.dev",
    topics: ["about", "projects", "background", "resume"],
    free: true,
  },
  {
    title: "Piyush Garg on Instagram",
    platform: "social",
    type: "handle",
    url: "https://www.instagram.com/piyushgarg.official/",
    topics: ["behind the scenes", "personal updates", "tech content"],
    free: true,
  },
  {
    title: "Piyush Garg on X",
    platform: "social",
    type: "handle",
    url: "https://x.com/piyushgarg_dev",
    topics: ["hot takes", "industry opinions", "quick updates"],
    free: true,
  },
  {
    title: "Piyush Garg on GitHub",
    platform: "social",
    type: "handle",
    url: "https://github.com/piyushgarg-dev",
    topics: ["open source", "code samples", "repositories"],
    free: true,
  },
  {
    title: "Piyush Garg on LinkedIn",
    platform: "social",
    type: "handle",
    url: "https://www.linkedin.com/in/piyushgargdev/",
    topics: ["professional updates", "career", "networking"],
    free: true,
  },
  {
    title: "The 'Is Dead' Series - JWT, Docker, REST API, Kubernetes, Nginx, Load Balancer",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCaD2wxnjJs26o3rTFdNah_",
    topics: ["jwt", "docker", "rest api", "kubernetes", "nginx", "load balancer"],
    free: true,
  },
  {
    title: "OpenAI Agents SDK with TypeScript",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sA-XUqy01s8yrZ0r0QZMpQT",
    topics: ["openai", "agents", "sdk", "llms", "genai"],
    free: true,
  },
  {
    title: "Master Agentic AI, Agentic Workflows & Generative AI",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCzJnjhtEZBpKGtC1Xk7z5Z",
    topics: ["agentic ai", "workflows", "generative ai", "llms", "genai"],
    free: true,
  },
  {
    title: "Master Docker - Containerization & Deployment",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDc2woh6XncR9_a310zaAyJ",
    topics: ["docker", "containers", "deployment", "aws", "ec2"],
    free: true,
  },
  {
    title: "System Design",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sBlBWRox2V2tg9QJ2zr4M3o",
    topics: ["system design", "scaling", "load balancers", "microservices", "databases"],
    free: true,
  },
  {
    title: "Complete Git & GitHub Tutorial",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCoLe5k0FWtFd-JykESyu6h",
    topics: ["git", "github", "version control", "collaboration"],
    free: true,
  },
  {
    title: "Master ReactJS - Advanced Concepts",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sBm5wu3ixPRQ0gDqHJUlxQf",
    topics: ["react", "frontend", "hooks", "state management", "advanced patterns"],
    free: true,
  },
  {
    title: "Nginx — Reverse Proxy & Load Balancing",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCbKdDspcuD3T6zFWPXzsNt",
    topics: ["nginx", "load balancing", "reverse proxy", "web server"],
    free: true,
  },
  {
    title: "Master NodeJS",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDby4Al-i13hQJGQoRQDfPo",
    topics: ["nodejs", "backend", "express", "rest api"],
    free: true,
  },
  {
    title: "Ultimate JavaScript Tutorials",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDFRdgPYvjnBs2JsDdHPIMv",
    topics: ["javascript", "js fundamentals", "frontend", "backend"],
    free: true,
  },
  {
    title: "Next.js Master Course",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDP2CHN5P0lDD64yYZ0Nn4J",
    topics: ["nextjs", "react", "server-side rendering", "frontend"],
    free: true,
  },
  {
    title: "React Tutorial - Beginner Friendly",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCHqHtgbjg1lSYgWebm1dyI",
    topics: ["react", "frontend", "hooks", "beginner"],
    free: true,
  },
  {
    title: "Piyush Garg - Paid Courses (Docker, Kafka, WebRTC, GenAI, Full Stack)",
    platform: "website",
    type: "course",
    url: "https://pro.piyushgarg.dev",
    topics: [
      "docker",
      "containers",
      "devops",
      "kafka",
      "message queues",
      "distributed systems",
      "webrtc",
      "real-time",
      "genai",
      "llms",
      "rag",
      "agents",
      "mcp",
      "nodejs",
      "backend",
      "nextjs",
      "react",
      "system design",
      "nginx",
      "load balancing",
    ],
    free: false,
  },
];
