import type { ReferenceItem } from "../types/chat.js";

export const PIYUSH_CATALOG: ReferenceItem[] = [
  {
    title: "Piyush Garg Website",
    platform: "website",
    type: "post",
    url: "https://www.piyushgarg.dev",
    topics: ["about", "projects", "background", "resume"],
    free: true,
  },
  {
    title: "Piyush Garg on Instagram",
    platform: "social",
    type: "handle",
    url: "https://www.instagram.com/piyushgarg.official/",
    topics: ["social", "content", "career", "projects"],
    free: true,
  },
  {
    title: "Piyush Garg on X",
    platform: "social",
    type: "handle",
    url: "https://x.com/piyushgarg_dev",
    topics: ["social", "content", "career", "projects"],
    free: true,
  },
  {
    title: "Piyush Garg on Github",
    platform: "social",
    type: "handle",
    url: "https://github.com/piyushgarg-dev",
    topics: ["open source", "code", "projects", "repos"],
    free: true,
  },
  {
    title: "Piyush Garg on LinkedIn",
    platform: "social",
    type: "handle",
    url: "https://www.linkedin.com/in/piyushgargdev/",
    topics: ["social", "content", "career", "projects"],
    free: true,
  },
  {
    title: "The Dead Series",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30s",
    topics: ["jwt", "docker", "restapi", "kubernetes", "nginx", "loadbalancer"],
    free: true,
  },
  {
    title: "OpenAI Agents SDK with Typescript",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sA-XUqy01s8yrZ0r0QZMpQT",
    topics: ["openai", "agents", "sdk", "llms", "genai"],
    free: true,
  },
  {
    title: "Master Agentic AI, Agentic Workflows and Generative AI",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCzJnjhtEZBpKGtC1Xk7z5Z",
    topics: ["agentic ai", "workflows", "generative ai", "llms", "genai"],
    free: true,
  },
  {
    title: "Master Docker Containerization & Deployment",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDc2woh6XncR9_a310zaAyJ",
    topics: ["docker", "containers", "deployment", "aws", "ec2"],
    free: true,
  },
  {
    title: "System Design",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sBlBWRox2V2tg9QJ2zr4M3o",
    topics: ["system design", "scaling", "load balancers", "microservices", "databases"],
    free: true,
  },
  {
    title: "Complete Git & GitHub Tutorial",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCoLe5k0FWtFd-JykESyu6h",
    topics: ["git", "github", "version control", "collaboration"],
    free: true,
  },
  {
    title: "Master ReactJS",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sBm5wu3ixPRQ0gDqHJUlxQf",
    topics: ["react", "frontend", "hooks", "state management"],
    free: true,
  },
  {
    title: "Nginx",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCbKdDspcuD3T6zFWPXzsNt",
    topics: ["nginx", "load balancing", "reverse proxy", "web server"],
    free: true,
  },
  {
    title: "Master NodeJS",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDby4Al-i13hQJGQoRQDfPo",
    topics: ["nodejs", "backend", "express", "rest api"],
    free: true,
  },
  {
    title: "Ultimate Javascript Tutorials",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDFRdgPYvjnBs2JsDdHPIMv",
    topics: ["javascript", "frontend", "backend", "web development"],
    free: true,
  },
  {
    title: "NextJS Master Course",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDP2CHN5P0lDD64yYZ0Nn4J",
    topics: ["nextjs", "react", "ssr", "frontend"],
    free: true,
  },
  {
    title: "React Tutorial",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sCHqHtgbjg1lSYgWebm1dyI",
    topics: ["react", "frontend", "hooks", "state management"],
    free: true,
  },
  {
    title: "Piyush Garg Courses",
    platform: "website",
    type: "course",
    url: "https://pro.piyushgarg.dev",
    topics: [
      "docker",
      "containers",
      "devops",
      "images",
      "open source",
      "github",
      "contributions",
      "career",
      "kafka",
      "message queues",
      "event streaming",
      "distributed systems",
      "webrtc",
      "real-time",
      "video calling",
      "peer to peer",
      "genai",
      "llms",
      "rag",
      "agents",
      "mcp",
      "javascript",
      "nodejs",
      "backend",
      "express",
      "rest api",
      "nextjs",
      "react",
      "ssr",
      "frontend",
      "hooks",
      "state management",
      "nginx",
      "load balancing",
      "reverse proxy",
      "web server",
    ],
    free: false,
  },
];
