import type { ReferenceItem } from "../types/chat.js";

export const PIYUSH_CATALOG: ReferenceItem[] = [
  {
    title: "Master NodeJS",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sDby4Al-i13hQJGQoRQDfPo",
    topics: ["nodejs", "backend", "express", "rest api"],
    free: true,
  },
  {
    title: "System Design",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/playlist?list=PLinedj3B30sBlBWRox2V2tg9QJ2zr4M3o",
    topics: ["system design", "scaling", "load balancers", "microservices", "databases"],
    free: true,
  },
  {
    title: "NextJS Master Course",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/@piyushgargdev",
    topics: ["nextjs", "react", "ssr", "frontend"],
    free: true,
  },
  {
    title: "Docker | Beginners to Advanced",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/@piyushgargdev",
    topics: ["docker", "containers", "devops", "images"],
    free: true,
  },
  {
    title: "Open Source Bootcamp",
    platform: "youtube",
    type: "playlist",
    url: "https://www.youtube.com/@piyushgargdev",
    topics: ["open source", "github", "contributions", "career"],
    free: true,
  },
  {
    title: "Kafka Deep Dive",
    platform: "youtube",
    type: "video",
    url: "https://www.youtube.com/@piyushgargdev",
    topics: ["kafka", "message queues", "event streaming", "distributed systems"],
    free: true,
  },
  {
    title: "WebRTC — Real-Time Video Apps",
    platform: "youtube",
    type: "series",
    url: "https://blog.piyushgarg.dev",
    topics: ["webrtc", "real-time", "video calling", "peer to peer"],
    free: true,
  },
  {
    title: "Full Stack GenAI Cohort — Forward Deployed Engineer",
    platform: "cohort",
    type: "course",
    url: "https://www.piyushgarg.dev",
    topics: ["genai", "llms", "rag", "agents", "mcp", "javascript"],
    free: false,
  },
  {
    title: "Full Stack Web Development Cohort",
    platform: "cohort",
    type: "course",
    url: "https://www.piyushgarg.dev",
    topics: ["full stack", "live cohort", "mentorship", "projects"],
    free: false,
  },
  {
    title: "Docker Course (Containers to Production)",
    platform: "cohort",
    type: "course",
    url: "https://pro.piyushgarg.dev",
    topics: ["docker", "containers", "aws ecs", "ecr", "deployment"],
    free: false,
  },
  {
    title: "System Design (Audio Course)",
    platform: "cohort",
    type: "course",
    url: "https://pro.piyushgarg.dev/learn/system-design-audio",
    topics: ["system design", "queues", "pub sub", "api gateway", "scaling"],
    free: false,
  },
  {
    title: "Full Stack GenAI with Python",
    platform: "udemy",
    type: "course",
    url: "https://www.udemy.com/user/piyush-garg-1163/",
    topics: ["genai", "python", "tokenization", "vector db", "rag", "agents"],
    free: false,
  },
  {
    title: "Node.js — From Scratch to Advanced",
    platform: "udemy",
    type: "course",
    url: "https://www.udemy.com/user/piyush-garg-1163/",
    topics: ["nodejs", "sql", "nosql", "mongodb", "express", "deployment"],
    free: false,
  },
  {
    title: "piyushgarg.dev",
    platform: "website",
    type: "post",
    url: "https://www.piyushgarg.dev",
    topics: ["about", "projects", "background", "resume"],
    free: true,
  },
  {
    title: "piyushgarg-dev on GitHub",
    platform: "github",
    type: "repo",
    url: "https://github.com/piyushgarg-dev",
    topics: ["open source", "code", "projects", "repos"],
    free: true,
  },
];
